name: Terraform AWS Deployment

on:
  push:
    branches:
      - main  # Run when code is pushed to 'main'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Export Terraform Variables
        run: |
          echo "TF_VAR_aws_region=${{ secrets.TF_VAR_vpc_cidr_block }}" >> $GITHUB_ENV
          echo "TF_VAR_pub_cidr_block=${{ secrets.TF_VAR_pub_cidr_block_a}}" >> $GITHUB_ENV
          echo "TF_VAR_pub_cidr_block_b=${{ secrets.TF_VAR_pub_cidr_block_b}}" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan # to destroy my resources.
        run: terraform plan -destroy -out=tfplan

      - name: Terraform destroy
        run: terraform apply -auto-approve tfplan
